services:
  ansible:
    build:
      context: ./ansible
      dockerfile: Dockerfile
    container_name: ansible
    networks:
      - ansible
    volumes:
      - ./ansible:/ansible
      - ./ansible/config/hosts:/etc/hosts
      - ./ansible/ssh:/ansible/ssh  # Mapeando o diretório de chaves SSH
    command: tail -f /dev/null
  
  worker1:
    build:
      context: .
      dockerfile: ./worker1/Dockerfile
    container_name: worker1
    networks:
      - ansible
    volumes:
      - ./ansible/ssh:/ansible/ssh  # Mapeando o diretório de chaves SSH com id_rsa.pub
    command: /bin/sh -c "mkdir -p /root/.ssh && cat /ansible/ssh/id_rsa.pub >> /root/.ssh/authorized_keys && tail -f /dev/null"

  worker2:
    build:
      context: .
      dockerfile: ./worker2/Dockerfile
    container_name: worker2
    networks:
      - ansible
    volumes:
      - ./ansible/ssh:/ansible/ssh  # Mapeando o diretório de chaves SSH com id_rsa.pub
    command: /bin/sh -c "mkdir -p /root/.ssh && cat /ansible/ssh/id_rsa.pub >> /root/.ssh/authorized_keys && tail -f /dev/null"

networks:
  ansible:
    driver: bridge
