services:
  ansible:
    build:
      context: ./ansible
      dockerfile: Dockerfile
    container_name: ansible
    networks:
      - ansible
    volumes:
      - ./ansible:/ansible
      - ./ansible/config/hosts:/etc/hosts
    command: tail -f /dev/null
  
  worker1:
    build:
      context: .
      dockerfile: ./worker1/Dockerfile
    container_name: worker1
    networks:
      - ansible
    command: tail -f /dev/null

  worker2:
    build:
      context: .
      dockerfile: ./worker2/Dockerfile
    container_name: worker2
    networks:
      - ansible
    command: tail -f /dev/null

networks:
  ansible:
    driver: bridge